const constants = Object.freeze({
    CONST_APP_VERSION: process.env.APP_VERSION,

    //RESPONSE CODES
    CONST_RESP_CODE_OK: 200,
    CONST_RESP_CODE_CONTENT_NOT_FOUND: 204,
    CONST_RESP_CODE_BAD_REQUEST: 400,
    CONST_RESP_CODE_UNAUTORIZE: 401,
    CONST_RESP_CODE_NOT_FOUND: 404,
    CONST_RESP_CODE_NOT_ACCEPT: 406,
    CONST_RESP_CODE_INTERNAL_SERVER_ERROR: 500
});

export default constants;